dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: HvX0CQwTKXApr3BAxHL0WXMqceHAjiJuDANZ4TraNLMZk+F7AQhgcL96XUWZN4BXjUNpaxKaS+TGjpF66BIXTazZEdyFr6y+YzGbwxJQ2mGNH16kBkFEWBDJSIRFyLWCiH9mvesRqUHXQcskdheNX011i3WhtYfFIf27GMPCrO4jmStEhpXH5u5LBhzm80U8YVw3/FrR1vPQVkGPtQ1iITqIKod5QtClLYSch3hO7FbTWp3tzUrMIB93tvj8PnDZRMQL/mm3y10ml7vyVHQ8TL6qNu/fF+MdnFcs8W2WZAz4t3uD1NzLitati1Dc0J4vqOLDHJ0yMWeKc637OZUrPDaEp8VWWPJzTUVqf0MqPdhjy6gWzqm8pWoCcgC6yjaMLEWmFE+Sd9ehulPZJexcCYUegZSy78U8Na2xHSbE2sGERVHmR9WtiGDxzi4vDCpX5DkRUGdTr5H4qnhq4tSjB8U+t05V5Q24oioXX87V3e0y2Ry8vsiY1tn/Q/XFqHj6qGvGvZTLPkjLlt/2nJRbgc+PtEbvhZcoggFeCDPWLZubi81S7/ZfMVmcgkIvG93BGurIbwrDyTvvhyRAoEG0MrcvZ88GFLTQwbSrTcxMO3/IbfJxRBKRY3nLB1X728WmuY080Nyi6HXb5WiIpU1upsP00bfs4BPCEBlrhXBoV88=
