comment:
  image:
    repository: rustsh
    tag: latest
  service:
    externalPort: 9292
    internalPort: 9292

post:
  image:
    repository: rustsh
    tag: latest
  service:
    externalPort: 5000
    internalPort: 5000

ui:
  image:
    repository: rustsh
    tag: latest
  service:
    externalPort: 9292
    internalPort: 9292
