global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#rustam_shaimardanov'
