version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - 9292:${UI_PORT}/tcp
    networks:
      - front-net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - front-net
      - back-net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - front-net
      - back-net

volumes:
  post_db:

networks:
  front-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back-net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
