version: '3.3'
services:
  post_db:
    image: mongo:3.2
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - 9292:${UI_PORT}/tcp
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front-net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front-net
      - back-net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front-net
      - back-net

volumes:
  post_db:

networks:
  front-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back-net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
