version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front-net
      - back-net

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.7.1
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.7.1
    ports:
      - "5601:5601"

networks:
  front-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back-net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
